In [7]:
import pandas as pd

## Reading the datasets

In [16]:
train = pd.read_csv('../data/train.csv')
test = pd.read_csv('../data/test.csv')

## merging datasets

In [27]:
df = pd.concat([train, test], ignore_index=True)

## Exploration & Cleaning

In [28]:
df.head()

,CustomerID,Age,Gender,Tenure,Usage Frequency,Support Calls,Payment Delay,Subscription Type,Contract Length,Total Spend,Last Interaction,Churn
0,2.0,30.0,Female,39.0,14.0,5.0,18.0,Standard,Annual,932.0,17.0,1.0
1,3.0,65.0,Female,49.0,1.0,10.0,8.0,Basic,Monthly,557.0,6.0,1.0
2,4.0,55.0,Female,14.0,4.0,6.0,18.0,Basic,Quarterly,185.0,3.0,1.0
3,5.0,58.0,Male,38.0,21.0,7.0,7.0,Standard,Monthly,396.0,29.0,1.0
4,6.0,23.0,Male,32.0,20.0,5.0,8.0,Basic,Monthly,617.0,20.0,1.0

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 505207 entries, 0 to 505206
Data columns (total 12 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   CustomerID         505206 non-null  float64
 1   Age                505206 non-null  float64
 2   Gender             505206 non-null  object
 3   Tenure             505206 non-null  float64
 4   Usage Frequency    505206 non-null  float64
 5   Support Calls      505206 non-null  float64
 6   Payment Delay      505206 non-null  float64
 7   Subscription Type  505206 non-null  object
 8   Contract Length    505206 non-null  object
 9   Total Spend        505206 non-null  float64
 10  Last Interaction   505206 non-null  float64
 11  Churn              505206 non-null  float64
dtypes: float64(9), object(3)
memory usage: 46.3+ MB

In [30]:
df.dropna(inplace=True)
df.describe()

,CustomerID,Age,Tenure,Usage Frequency,Support Calls,Payment Delay,Total Spend,Last Interaction,Churn
count,505206.000000,505206.000000,505206.000000,505206.000000,505206.000000,505206.000000,505206.000000,505206.000000,505206.000000
mean,200779.451782,39.704172,31.350435,15.714825,3.833317,13.496843,620.072766,14.610581,0.555203
std,137241.343095,12.670577,17.237482,8.619323,3.133603,8.451187,245.319256,8.608286,0.496944
min,1.000000,18.000000,1.000000,1.000000,0.000000,0.000000,100.000000,1.000000,0.000000
25%,63827.250000,29.000000,16.000000,8.000000,1.000000,6.000000,446.000000,7.000000,0.000000
50%,193039.500000,40.000000,32.000000,16.000000,3.000000,13.000000,648.900000,14.000000,1.000000
75%,321645.750000,49.000000,46.000000,23.000000,6.000000,20.000000,824.000000,22.000000,1.000000
max,449999.000000,65.000000,60.000000,30.000000,10.000000,30.000000,1000.000000,30.000000,1.000000

In [31]:
df.describe(include='object')

        Gender Subscription Type Contract Length
count   505206            505206          505206
unique       2                 3               3
top       Male          Standard          Annual
freq    280273            170630          198608

In [32]:
df = df.drop(columns=['CustomerID'])

In [33]:
df.duplicated().sum()

np.int64(0)

In [34]:
cat_cols =['Gender','Subscription Type','Contract Length']
for col in cat_cols:
    print(f"Value counts for {col}:\n{df[col].value_counts()}\n")

Value counts for Gender:
Gender
Male      280273
Female    224933
Name: count, dtype: int64

Value counts for Subscription Type:
Subscription Type
Standard    170630
Premium     170099
Basic       164477
Name: count, dtype: int64

Value counts for Contract Length:
Contract Length
Annual       198608
Quarterly    197364
Monthly      109234
Name: count, dtype: int64

In [35]:
float_cols = df.select_dtypes(include=['float']).columns
for col in float_cols:
    df[col] = df[col].astype(int)
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 505206 entries, 0 to 505206
Data columns (total 11 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Age                505206 non-null  int64
 1   Gender             505206 non-null  object
 2   Tenure             505206 non-null  int64
 3   Usage Frequency    505206 non-null  int64
 4   Support Calls      505206 non-null  int64
 5   Payment Delay      505206 non-null  int64
 6   Subscription Type  505206 non-null  object
 7   Contract Length    505206 non-null  object
 8   Total Spend        505206 non-null  int64
 9   Last Interaction   505206 non-null  int64
 10  Churn              505206 non-null  int64
dtypes: int64(8), object(3)
memory usage: 46.3+ MB

In [36]:
df.to_csv('../data/cleaned_data.csv', index=False)